package pers.guanzf.common.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import pers.guanzf.common.core.model.FriendExample;
import pers.guanzf.common.core.model.info.FriendInfo;

public interface FriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    long countByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    int deleteByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    int insert(FriendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    int insertSelective(FriendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    List<FriendInfo> selectByExample(FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    FriendInfo selectByPrimaryKey(String friendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FriendInfo record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FriendInfo record, @Param("example") FriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FriendInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_friend
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FriendInfo record);
}