package pers.guanzf.common.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.guanzf.common.core.model.MessageManageExample;
import pers.guanzf.common.core.model.info.MessageManageInfo;

public interface MessageManageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    long countByExample(MessageManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    int deleteByExample(MessageManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    int insert(MessageManageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    int insertSelective(MessageManageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    List<MessageManageInfo> selectByExample(MessageManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    MessageManageInfo selectByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MessageManageInfo record, @Param("example") MessageManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MessageManageInfo record, @Param("example") MessageManageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessageManageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessageManageInfo record);
}