package pers.guanzf.common.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.guanzf.common.core.model.PersonExample;
import pers.guanzf.common.core.model.info.PersonInfo;

public interface PersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    int insert(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    int insertSelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    List<PersonInfo> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    PersonInfo selectByPrimaryKey(String personId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PersonInfo record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PersonInfo record, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PersonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PersonInfo record);
}