package pers.guanzf.common.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.guanzf.common.core.model.SysDictExample;
import pers.guanzf.common.core.model.info.SysDictInfo;

public interface SysDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    long countByExample(SysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    int deleteByExample(SysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sysDictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    int insert(SysDictInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    int insertSelective(SysDictInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    List<SysDictInfo> selectByExample(SysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    SysDictInfo selectByPrimaryKey(String sysDictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysDictInfo record, @Param("example") SysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysDictInfo record, @Param("example") SysDictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysDictInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysDictInfo record);
}