package pers.guanzf.common.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PersonProduceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public PersonProduceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPersonProduceIdIsNull() {
            addCriterion("PERSON_PRODUCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdIsNotNull() {
            addCriterion("PERSON_PRODUCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdEqualTo(String value) {
            addCriterion("PERSON_PRODUCE_ID =", value, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdNotEqualTo(String value) {
            addCriterion("PERSON_PRODUCE_ID <>", value, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdGreaterThan(String value) {
            addCriterion("PERSON_PRODUCE_ID >", value, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdGreaterThanOrEqualTo(String value) {
            addCriterion("PERSON_PRODUCE_ID >=", value, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdLessThan(String value) {
            addCriterion("PERSON_PRODUCE_ID <", value, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdLessThanOrEqualTo(String value) {
            addCriterion("PERSON_PRODUCE_ID <=", value, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdLike(String value) {
            addCriterion("PERSON_PRODUCE_ID like", value, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdNotLike(String value) {
            addCriterion("PERSON_PRODUCE_ID not like", value, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdIn(List<String> values) {
            addCriterion("PERSON_PRODUCE_ID in", values, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdNotIn(List<String> values) {
            addCriterion("PERSON_PRODUCE_ID not in", values, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdBetween(String value1, String value2) {
            addCriterion("PERSON_PRODUCE_ID between", value1, value2, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonProduceIdNotBetween(String value1, String value2) {
            addCriterion("PERSON_PRODUCE_ID not between", value1, value2, "personProduceId");
            return (Criteria) this;
        }

        public Criteria andPersonIdIsNull() {
            addCriterion("PERSON_ID is null");
            return (Criteria) this;
        }

        public Criteria andPersonIdIsNotNull() {
            addCriterion("PERSON_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPersonIdEqualTo(String value) {
            addCriterion("PERSON_ID =", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotEqualTo(String value) {
            addCriterion("PERSON_ID <>", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdGreaterThan(String value) {
            addCriterion("PERSON_ID >", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdGreaterThanOrEqualTo(String value) {
            addCriterion("PERSON_ID >=", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLessThan(String value) {
            addCriterion("PERSON_ID <", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLessThanOrEqualTo(String value) {
            addCriterion("PERSON_ID <=", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdLike(String value) {
            addCriterion("PERSON_ID like", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotLike(String value) {
            addCriterion("PERSON_ID not like", value, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdIn(List<String> values) {
            addCriterion("PERSON_ID in", values, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotIn(List<String> values) {
            addCriterion("PERSON_ID not in", values, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdBetween(String value1, String value2) {
            addCriterion("PERSON_ID between", value1, value2, "personId");
            return (Criteria) this;
        }

        public Criteria andPersonIdNotBetween(String value1, String value2) {
            addCriterion("PERSON_ID not between", value1, value2, "personId");
            return (Criteria) this;
        }

        public Criteria andProduceIdIsNull() {
            addCriterion("PRODUCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andProduceIdIsNotNull() {
            addCriterion("PRODUCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andProduceIdEqualTo(String value) {
            addCriterion("PRODUCE_ID =", value, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdNotEqualTo(String value) {
            addCriterion("PRODUCE_ID <>", value, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdGreaterThan(String value) {
            addCriterion("PRODUCE_ID >", value, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCE_ID >=", value, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdLessThan(String value) {
            addCriterion("PRODUCE_ID <", value, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdLessThanOrEqualTo(String value) {
            addCriterion("PRODUCE_ID <=", value, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdLike(String value) {
            addCriterion("PRODUCE_ID like", value, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdNotLike(String value) {
            addCriterion("PRODUCE_ID not like", value, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdIn(List<String> values) {
            addCriterion("PRODUCE_ID in", values, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdNotIn(List<String> values) {
            addCriterion("PRODUCE_ID not in", values, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdBetween(String value1, String value2) {
            addCriterion("PRODUCE_ID between", value1, value2, "produceId");
            return (Criteria) this;
        }

        public Criteria andProduceIdNotBetween(String value1, String value2) {
            addCriterion("PRODUCE_ID not between", value1, value2, "produceId");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlIsNull() {
            addCriterion("COMMENT_IMG_URL is null");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlIsNotNull() {
            addCriterion("COMMENT_IMG_URL is not null");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlEqualTo(String value) {
            addCriterion("COMMENT_IMG_URL =", value, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlNotEqualTo(String value) {
            addCriterion("COMMENT_IMG_URL <>", value, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlGreaterThan(String value) {
            addCriterion("COMMENT_IMG_URL >", value, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT_IMG_URL >=", value, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlLessThan(String value) {
            addCriterion("COMMENT_IMG_URL <", value, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlLessThanOrEqualTo(String value) {
            addCriterion("COMMENT_IMG_URL <=", value, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlLike(String value) {
            addCriterion("COMMENT_IMG_URL like", value, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlNotLike(String value) {
            addCriterion("COMMENT_IMG_URL not like", value, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlIn(List<String> values) {
            addCriterion("COMMENT_IMG_URL in", values, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlNotIn(List<String> values) {
            addCriterion("COMMENT_IMG_URL not in", values, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlBetween(String value1, String value2) {
            addCriterion("COMMENT_IMG_URL between", value1, value2, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentImgUrlNotBetween(String value1, String value2) {
            addCriterion("COMMENT_IMG_URL not between", value1, value2, "commentImgUrl");
            return (Criteria) this;
        }

        public Criteria andCommentValueIsNull() {
            addCriterion("COMMENT_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andCommentValueIsNotNull() {
            addCriterion("COMMENT_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andCommentValueEqualTo(Float value) {
            addCriterion("COMMENT_VALUE =", value, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueNotEqualTo(Float value) {
            addCriterion("COMMENT_VALUE <>", value, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueGreaterThan(Float value) {
            addCriterion("COMMENT_VALUE >", value, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueGreaterThanOrEqualTo(Float value) {
            addCriterion("COMMENT_VALUE >=", value, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueLessThan(Float value) {
            addCriterion("COMMENT_VALUE <", value, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueLessThanOrEqualTo(Float value) {
            addCriterion("COMMENT_VALUE <=", value, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueIn(List<Float> values) {
            addCriterion("COMMENT_VALUE in", values, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueNotIn(List<Float> values) {
            addCriterion("COMMENT_VALUE not in", values, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueBetween(Float value1, Float value2) {
            addCriterion("COMMENT_VALUE between", value1, value2, "commentValue");
            return (Criteria) this;
        }

        public Criteria andCommentValueNotBetween(Float value1, Float value2) {
            addCriterion("COMMENT_VALUE not between", value1, value2, "commentValue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_person_produce
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}