package pers.guanzf.common.core.model;

public class SysDict {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_dict.SYS_DICT_ID
     *
     * @mbg.generated
     */
    private String sysDictId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_dict.SYS_DICT_NAME
     *
     * @mbg.generated
     */
    private String sysDictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_dict.SYS_DICT_TYPE
     *
     * @mbg.generated
     */
    private String sysDictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_dict.SYS_DICT_VALUE
     *
     * @mbg.generated
     */
    private Integer sysDictValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_dict.SYS_DICT_SORT
     *
     * @mbg.generated
     */
    private Integer sysDictSort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_dict.SYS_DICT_TYPE_DESC
     *
     * @mbg.generated
     */
    private String sysDictTypeDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_sys_dict.SYS_DICT_EDITABLE
     *
     * @mbg.generated
     */
    private Integer sysDictEditable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_dict.SYS_DICT_ID
     *
     * @return the value of g_sys_dict.SYS_DICT_ID
     *
     * @mbg.generated
     */
    public String getSysDictId() {
        return sysDictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_dict.SYS_DICT_ID
     *
     * @param sysDictId the value for g_sys_dict.SYS_DICT_ID
     *
     * @mbg.generated
     */
    public void setSysDictId(String sysDictId) {
        this.sysDictId = sysDictId == null ? null : sysDictId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_dict.SYS_DICT_NAME
     *
     * @return the value of g_sys_dict.SYS_DICT_NAME
     *
     * @mbg.generated
     */
    public String getSysDictName() {
        return sysDictName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_dict.SYS_DICT_NAME
     *
     * @param sysDictName the value for g_sys_dict.SYS_DICT_NAME
     *
     * @mbg.generated
     */
    public void setSysDictName(String sysDictName) {
        this.sysDictName = sysDictName == null ? null : sysDictName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_dict.SYS_DICT_TYPE
     *
     * @return the value of g_sys_dict.SYS_DICT_TYPE
     *
     * @mbg.generated
     */
    public String getSysDictType() {
        return sysDictType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_dict.SYS_DICT_TYPE
     *
     * @param sysDictType the value for g_sys_dict.SYS_DICT_TYPE
     *
     * @mbg.generated
     */
    public void setSysDictType(String sysDictType) {
        this.sysDictType = sysDictType == null ? null : sysDictType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_dict.SYS_DICT_VALUE
     *
     * @return the value of g_sys_dict.SYS_DICT_VALUE
     *
     * @mbg.generated
     */
    public Integer getSysDictValue() {
        return sysDictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_dict.SYS_DICT_VALUE
     *
     * @param sysDictValue the value for g_sys_dict.SYS_DICT_VALUE
     *
     * @mbg.generated
     */
    public void setSysDictValue(Integer sysDictValue) {
        this.sysDictValue = sysDictValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_dict.SYS_DICT_SORT
     *
     * @return the value of g_sys_dict.SYS_DICT_SORT
     *
     * @mbg.generated
     */
    public Integer getSysDictSort() {
        return sysDictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_dict.SYS_DICT_SORT
     *
     * @param sysDictSort the value for g_sys_dict.SYS_DICT_SORT
     *
     * @mbg.generated
     */
    public void setSysDictSort(Integer sysDictSort) {
        this.sysDictSort = sysDictSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_dict.SYS_DICT_TYPE_DESC
     *
     * @return the value of g_sys_dict.SYS_DICT_TYPE_DESC
     *
     * @mbg.generated
     */
    public String getSysDictTypeDesc() {
        return sysDictTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_dict.SYS_DICT_TYPE_DESC
     *
     * @param sysDictTypeDesc the value for g_sys_dict.SYS_DICT_TYPE_DESC
     *
     * @mbg.generated
     */
    public void setSysDictTypeDesc(String sysDictTypeDesc) {
        this.sysDictTypeDesc = sysDictTypeDesc == null ? null : sysDictTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_sys_dict.SYS_DICT_EDITABLE
     *
     * @return the value of g_sys_dict.SYS_DICT_EDITABLE
     *
     * @mbg.generated
     */
    public Integer getSysDictEditable() {
        return sysDictEditable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_sys_dict.SYS_DICT_EDITABLE
     *
     * @param sysDictEditable the value for g_sys_dict.SYS_DICT_EDITABLE
     *
     * @mbg.generated
     */
    public void setSysDictEditable(Integer sysDictEditable) {
        this.sysDictEditable = sysDictEditable;
    }
}