package pers.guanzf.common.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.guanzf.common.core.model.CommodityStructrueExample;
import pers.guanzf.common.core.model.info.CommodityStructrueInfo;

public interface CommodityStructrueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    long countByExample(CommodityStructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    int deleteByExample(CommodityStructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String commodityStructrueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    int insert(CommodityStructrueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    int insertSelective(CommodityStructrueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    List<CommodityStructrueInfo> selectByExample(CommodityStructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    CommodityStructrueInfo selectByPrimaryKey(String commodityStructrueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CommodityStructrueInfo record, @Param("example") CommodityStructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CommodityStructrueInfo record, @Param("example") CommodityStructrueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CommodityStructrueInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CommodityStructrueInfo record);
}