package pers.guanzf.common.core.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.USER_ID
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.USER_NAME
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.USER_PASSWORD
     *
     * @mbg.generated
     */
    private String userPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.USER_IMG
     *
     * @mbg.generated
     */
    private String userImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.NOTES
     *
     * @mbg.generated
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.PERSON_ID
     *
     * @mbg.generated
     */
    private String personId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.REG_SUCCESS
     *
     * @mbg.generated
     */
    private String regSuccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.USER_TYPE
     *
     * @mbg.generated
     */
    private String userType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_user.USER_TEMPLATE_IMG
     *
     * @mbg.generated
     */
    private byte[] userTemplateImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.USER_ID
     *
     * @return the value of g_user.USER_ID
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.USER_ID
     *
     * @param userId the value for g_user.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.USER_NAME
     *
     * @return the value of g_user.USER_NAME
     *
     * @mbg.generated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.USER_NAME
     *
     * @param userName the value for g_user.USER_NAME
     *
     * @mbg.generated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.USER_PASSWORD
     *
     * @return the value of g_user.USER_PASSWORD
     *
     * @mbg.generated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.USER_PASSWORD
     *
     * @param userPassword the value for g_user.USER_PASSWORD
     *
     * @mbg.generated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.USER_IMG
     *
     * @return the value of g_user.USER_IMG
     *
     * @mbg.generated
     */
    public String getUserImg() {
        return userImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.USER_IMG
     *
     * @param userImg the value for g_user.USER_IMG
     *
     * @mbg.generated
     */
    public void setUserImg(String userImg) {
        this.userImg = userImg == null ? null : userImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.UPDATE_TIME
     *
     * @return the value of g_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.UPDATE_TIME
     *
     * @param updateTime the value for g_user.UPDATE_TIME
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.NOTES
     *
     * @return the value of g_user.NOTES
     *
     * @mbg.generated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.NOTES
     *
     * @param notes the value for g_user.NOTES
     *
     * @mbg.generated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.PERSON_ID
     *
     * @return the value of g_user.PERSON_ID
     *
     * @mbg.generated
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.PERSON_ID
     *
     * @param personId the value for g_user.PERSON_ID
     *
     * @mbg.generated
     */
    public void setPersonId(String personId) {
        this.personId = personId == null ? null : personId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.REG_SUCCESS
     *
     * @return the value of g_user.REG_SUCCESS
     *
     * @mbg.generated
     */
    public String getRegSuccess() {
        return regSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.REG_SUCCESS
     *
     * @param regSuccess the value for g_user.REG_SUCCESS
     *
     * @mbg.generated
     */
    public void setRegSuccess(String regSuccess) {
        this.regSuccess = regSuccess == null ? null : regSuccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.USER_TYPE
     *
     * @return the value of g_user.USER_TYPE
     *
     * @mbg.generated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.USER_TYPE
     *
     * @param userType the value for g_user.USER_TYPE
     *
     * @mbg.generated
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_user.USER_TEMPLATE_IMG
     *
     * @return the value of g_user.USER_TEMPLATE_IMG
     *
     * @mbg.generated
     */
    public byte[] getUserTemplateImg() {
        return userTemplateImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_user.USER_TEMPLATE_IMG
     *
     * @param userTemplateImg the value for g_user.USER_TEMPLATE_IMG
     *
     * @mbg.generated
     */
    public void setUserTemplateImg(byte[] userTemplateImg) {
        this.userTemplateImg = userTemplateImg;
    }
}