package pers.guanzf.common.core.model;

public class CommodityStructrue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_commodity_structrue.COMMODITY_STRUCTRUE_ID
     *
     * @mbg.generated
     */
    private String commodityStructrueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_commodity_structrue.COMMODITY_STRUCTRUE_NAME
     *
     * @mbg.generated
     */
    private String commodityStructrueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_commodity_structrue.COMMODITY_STRUCTRUE_FARTHER_ID
     *
     * @mbg.generated
     */
    private String commodityStructrueFartherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_commodity_structrue.COMMODITY_STRUCTRUE_CHILD_NUM
     *
     * @mbg.generated
     */
    private Integer commodityStructrueChildNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_commodity_structrue.COMMODITY_STRUCTRUE_ID
     *
     * @return the value of g_commodity_structrue.COMMODITY_STRUCTRUE_ID
     *
     * @mbg.generated
     */
    public String getCommodityStructrueId() {
        return commodityStructrueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_commodity_structrue.COMMODITY_STRUCTRUE_ID
     *
     * @param commodityStructrueId the value for g_commodity_structrue.COMMODITY_STRUCTRUE_ID
     *
     * @mbg.generated
     */
    public void setCommodityStructrueId(String commodityStructrueId) {
        this.commodityStructrueId = commodityStructrueId == null ? null : commodityStructrueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_commodity_structrue.COMMODITY_STRUCTRUE_NAME
     *
     * @return the value of g_commodity_structrue.COMMODITY_STRUCTRUE_NAME
     *
     * @mbg.generated
     */
    public String getCommodityStructrueName() {
        return commodityStructrueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_commodity_structrue.COMMODITY_STRUCTRUE_NAME
     *
     * @param commodityStructrueName the value for g_commodity_structrue.COMMODITY_STRUCTRUE_NAME
     *
     * @mbg.generated
     */
    public void setCommodityStructrueName(String commodityStructrueName) {
        this.commodityStructrueName = commodityStructrueName == null ? null : commodityStructrueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_commodity_structrue.COMMODITY_STRUCTRUE_FARTHER_ID
     *
     * @return the value of g_commodity_structrue.COMMODITY_STRUCTRUE_FARTHER_ID
     *
     * @mbg.generated
     */
    public String getCommodityStructrueFartherId() {
        return commodityStructrueFartherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_commodity_structrue.COMMODITY_STRUCTRUE_FARTHER_ID
     *
     * @param commodityStructrueFartherId the value for g_commodity_structrue.COMMODITY_STRUCTRUE_FARTHER_ID
     *
     * @mbg.generated
     */
    public void setCommodityStructrueFartherId(String commodityStructrueFartherId) {
        this.commodityStructrueFartherId = commodityStructrueFartherId == null ? null : commodityStructrueFartherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_commodity_structrue.COMMODITY_STRUCTRUE_CHILD_NUM
     *
     * @return the value of g_commodity_structrue.COMMODITY_STRUCTRUE_CHILD_NUM
     *
     * @mbg.generated
     */
    public Integer getCommodityStructrueChildNum() {
        return commodityStructrueChildNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_commodity_structrue.COMMODITY_STRUCTRUE_CHILD_NUM
     *
     * @param commodityStructrueChildNum the value for g_commodity_structrue.COMMODITY_STRUCTRUE_CHILD_NUM
     *
     * @mbg.generated
     */
    public void setCommodityStructrueChildNum(Integer commodityStructrueChildNum) {
        this.commodityStructrueChildNum = commodityStructrueChildNum;
    }
}