package pers.guanzf.common.core.model;

import java.util.Date;

public class Friend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_friend.FRIEND_ID
     *
     * @mbg.generated
     */
    private String friendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_friend.FRIEND_MY_ID
     *
     * @mbg.generated
     */
    private String friendMyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_friend.FRIEND_FRIEND_ID
     *
     * @mbg.generated
     */
    private String friendFriendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_friend.FRIEND_SIMILARITY_DEGREE
     *
     * @mbg.generated
     */
    private Float friendSimilarityDegree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_friend.FRIEND_CREATE_TIME
     *
     * @mbg.generated
     */
    private Date friendCreateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_friend.FRIEND_DISABLE
     *
     * @mbg.generated
     */
    private String friendDisable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_friend.FRIEND_ID
     *
     * @return the value of g_friend.FRIEND_ID
     *
     * @mbg.generated
     */
    public String getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_friend.FRIEND_ID
     *
     * @param friendId the value for g_friend.FRIEND_ID
     *
     * @mbg.generated
     */
    public void setFriendId(String friendId) {
        this.friendId = friendId == null ? null : friendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_friend.FRIEND_MY_ID
     *
     * @return the value of g_friend.FRIEND_MY_ID
     *
     * @mbg.generated
     */
    public String getFriendMyId() {
        return friendMyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_friend.FRIEND_MY_ID
     *
     * @param friendMyId the value for g_friend.FRIEND_MY_ID
     *
     * @mbg.generated
     */
    public void setFriendMyId(String friendMyId) {
        this.friendMyId = friendMyId == null ? null : friendMyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_friend.FRIEND_FRIEND_ID
     *
     * @return the value of g_friend.FRIEND_FRIEND_ID
     *
     * @mbg.generated
     */
    public String getFriendFriendId() {
        return friendFriendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_friend.FRIEND_FRIEND_ID
     *
     * @param friendFriendId the value for g_friend.FRIEND_FRIEND_ID
     *
     * @mbg.generated
     */
    public void setFriendFriendId(String friendFriendId) {
        this.friendFriendId = friendFriendId == null ? null : friendFriendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_friend.FRIEND_SIMILARITY_DEGREE
     *
     * @return the value of g_friend.FRIEND_SIMILARITY_DEGREE
     *
     * @mbg.generated
     */
    public Float getFriendSimilarityDegree() {
        return friendSimilarityDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_friend.FRIEND_SIMILARITY_DEGREE
     *
     * @param friendSimilarityDegree the value for g_friend.FRIEND_SIMILARITY_DEGREE
     *
     * @mbg.generated
     */
    public void setFriendSimilarityDegree(Float friendSimilarityDegree) {
        this.friendSimilarityDegree = friendSimilarityDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_friend.FRIEND_CREATE_TIME
     *
     * @return the value of g_friend.FRIEND_CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getFriendCreateTime() {
        return friendCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_friend.FRIEND_CREATE_TIME
     *
     * @param friendCreateTime the value for g_friend.FRIEND_CREATE_TIME
     *
     * @mbg.generated
     */
    public void setFriendCreateTime(Date friendCreateTime) {
        this.friendCreateTime = friendCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_friend.FRIEND_DISABLE
     *
     * @return the value of g_friend.FRIEND_DISABLE
     *
     * @mbg.generated
     */
    public String getFriendDisable() {
        return friendDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_friend.FRIEND_DISABLE
     *
     * @param friendDisable the value for g_friend.FRIEND_DISABLE
     *
     * @mbg.generated
     */
    public void setFriendDisable(String friendDisable) {
        this.friendDisable = friendDisable == null ? null : friendDisable.trim();
    }
}