package pers.guanzf.common.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.guanzf.common.core.model.PersonProduce;
import pers.guanzf.common.core.model.PersonProduceExample;

public interface PersonProduceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    long countByExample(PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int deleteByExample(PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String personProduceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int insert(PersonProduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int insertSelective(PersonProduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    List<PersonProduce> selectByExample(PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    PersonProduce selectByPrimaryKey(String personProduceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PersonProduce record, @Param("example") PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PersonProduce record, @Param("example") PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PersonProduce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PersonProduce record);
}