package pers.guanzf.common.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MessageManageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public MessageManageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMessageIdIsNull() {
            addCriterion("MESSAGE_ID is null");
            return (Criteria) this;
        }

        public Criteria andMessageIdIsNotNull() {
            addCriterion("MESSAGE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMessageIdEqualTo(String value) {
            addCriterion("MESSAGE_ID =", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotEqualTo(String value) {
            addCriterion("MESSAGE_ID <>", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThan(String value) {
            addCriterion("MESSAGE_ID >", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE_ID >=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThan(String value) {
            addCriterion("MESSAGE_ID <", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE_ID <=", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdLike(String value) {
            addCriterion("MESSAGE_ID like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotLike(String value) {
            addCriterion("MESSAGE_ID not like", value, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdIn(List<String> values) {
            addCriterion("MESSAGE_ID in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotIn(List<String> values) {
            addCriterion("MESSAGE_ID not in", values, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdBetween(String value1, String value2) {
            addCriterion("MESSAGE_ID between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessageIdNotBetween(String value1, String value2) {
            addCriterion("MESSAGE_ID not between", value1, value2, "messageId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdIsNull() {
            addCriterion("MESSAGE_PERSON_ID is null");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdIsNotNull() {
            addCriterion("MESSAGE_PERSON_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdEqualTo(String value) {
            addCriterion("MESSAGE_PERSON_ID =", value, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdNotEqualTo(String value) {
            addCriterion("MESSAGE_PERSON_ID <>", value, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdGreaterThan(String value) {
            addCriterion("MESSAGE_PERSON_ID >", value, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE_PERSON_ID >=", value, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdLessThan(String value) {
            addCriterion("MESSAGE_PERSON_ID <", value, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE_PERSON_ID <=", value, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdLike(String value) {
            addCriterion("MESSAGE_PERSON_ID like", value, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdNotLike(String value) {
            addCriterion("MESSAGE_PERSON_ID not like", value, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdIn(List<String> values) {
            addCriterion("MESSAGE_PERSON_ID in", values, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdNotIn(List<String> values) {
            addCriterion("MESSAGE_PERSON_ID not in", values, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdBetween(String value1, String value2) {
            addCriterion("MESSAGE_PERSON_ID between", value1, value2, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessagePersonIdNotBetween(String value1, String value2) {
            addCriterion("MESSAGE_PERSON_ID not between", value1, value2, "messagePersonId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdIsNull() {
            addCriterion("MESSAGE_PRODUCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdIsNotNull() {
            addCriterion("MESSAGE_PRODUCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdEqualTo(String value) {
            addCriterion("MESSAGE_PRODUCE_ID =", value, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdNotEqualTo(String value) {
            addCriterion("MESSAGE_PRODUCE_ID <>", value, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdGreaterThan(String value) {
            addCriterion("MESSAGE_PRODUCE_ID >", value, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE_PRODUCE_ID >=", value, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdLessThan(String value) {
            addCriterion("MESSAGE_PRODUCE_ID <", value, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE_PRODUCE_ID <=", value, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdLike(String value) {
            addCriterion("MESSAGE_PRODUCE_ID like", value, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdNotLike(String value) {
            addCriterion("MESSAGE_PRODUCE_ID not like", value, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdIn(List<String> values) {
            addCriterion("MESSAGE_PRODUCE_ID in", values, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdNotIn(List<String> values) {
            addCriterion("MESSAGE_PRODUCE_ID not in", values, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdBetween(String value1, String value2) {
            addCriterion("MESSAGE_PRODUCE_ID between", value1, value2, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageProduceIdNotBetween(String value1, String value2) {
            addCriterion("MESSAGE_PRODUCE_ID not between", value1, value2, "messageProduceId");
            return (Criteria) this;
        }

        public Criteria andMessageInfoIsNull() {
            addCriterion("MESSAGE_INFO is null");
            return (Criteria) this;
        }

        public Criteria andMessageInfoIsNotNull() {
            addCriterion("MESSAGE_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andMessageInfoEqualTo(String value) {
            addCriterion("MESSAGE_INFO =", value, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoNotEqualTo(String value) {
            addCriterion("MESSAGE_INFO <>", value, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoGreaterThan(String value) {
            addCriterion("MESSAGE_INFO >", value, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE_INFO >=", value, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoLessThan(String value) {
            addCriterion("MESSAGE_INFO <", value, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE_INFO <=", value, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoLike(String value) {
            addCriterion("MESSAGE_INFO like", value, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoNotLike(String value) {
            addCriterion("MESSAGE_INFO not like", value, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoIn(List<String> values) {
            addCriterion("MESSAGE_INFO in", values, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoNotIn(List<String> values) {
            addCriterion("MESSAGE_INFO not in", values, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoBetween(String value1, String value2) {
            addCriterion("MESSAGE_INFO between", value1, value2, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageInfoNotBetween(String value1, String value2) {
            addCriterion("MESSAGE_INFO not between", value1, value2, "messageInfo");
            return (Criteria) this;
        }

        public Criteria andMessageDateIsNull() {
            addCriterion("MESSAGE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andMessageDateIsNotNull() {
            addCriterion("MESSAGE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andMessageDateEqualTo(Date value) {
            addCriterion("MESSAGE_DATE =", value, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateNotEqualTo(Date value) {
            addCriterion("MESSAGE_DATE <>", value, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateGreaterThan(Date value) {
            addCriterion("MESSAGE_DATE >", value, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateGreaterThanOrEqualTo(Date value) {
            addCriterion("MESSAGE_DATE >=", value, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateLessThan(Date value) {
            addCriterion("MESSAGE_DATE <", value, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateLessThanOrEqualTo(Date value) {
            addCriterion("MESSAGE_DATE <=", value, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateIn(List<Date> values) {
            addCriterion("MESSAGE_DATE in", values, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateNotIn(List<Date> values) {
            addCriterion("MESSAGE_DATE not in", values, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateBetween(Date value1, Date value2) {
            addCriterion("MESSAGE_DATE between", value1, value2, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDateNotBetween(Date value1, Date value2) {
            addCriterion("MESSAGE_DATE not between", value1, value2, "messageDate");
            return (Criteria) this;
        }

        public Criteria andMessageDisableIsNull() {
            addCriterion("MESSAGE_DISABLE is null");
            return (Criteria) this;
        }

        public Criteria andMessageDisableIsNotNull() {
            addCriterion("MESSAGE_DISABLE is not null");
            return (Criteria) this;
        }

        public Criteria andMessageDisableEqualTo(String value) {
            addCriterion("MESSAGE_DISABLE =", value, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableNotEqualTo(String value) {
            addCriterion("MESSAGE_DISABLE <>", value, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableGreaterThan(String value) {
            addCriterion("MESSAGE_DISABLE >", value, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableGreaterThanOrEqualTo(String value) {
            addCriterion("MESSAGE_DISABLE >=", value, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableLessThan(String value) {
            addCriterion("MESSAGE_DISABLE <", value, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableLessThanOrEqualTo(String value) {
            addCriterion("MESSAGE_DISABLE <=", value, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableLike(String value) {
            addCriterion("MESSAGE_DISABLE like", value, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableNotLike(String value) {
            addCriterion("MESSAGE_DISABLE not like", value, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableIn(List<String> values) {
            addCriterion("MESSAGE_DISABLE in", values, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableNotIn(List<String> values) {
            addCriterion("MESSAGE_DISABLE not in", values, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableBetween(String value1, String value2) {
            addCriterion("MESSAGE_DISABLE between", value1, value2, "messageDisable");
            return (Criteria) this;
        }

        public Criteria andMessageDisableNotBetween(String value1, String value2) {
            addCriterion("MESSAGE_DISABLE not between", value1, value2, "messageDisable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_message_manage
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_message_manage
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}