package pers.guanzf.common.core.model;

import java.util.Date;

public class MessageManage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_message_manage.MESSAGE_ID
     *
     * @mbg.generated
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_message_manage.MESSAGE_PERSON_ID
     *
     * @mbg.generated
     */
    private String messagePersonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_message_manage.MESSAGE_PRODUCE_ID
     *
     * @mbg.generated
     */
    private String messageProduceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_message_manage.MESSAGE_INFO
     *
     * @mbg.generated
     */
    private String messageInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_message_manage.MESSAGE_DATE
     *
     * @mbg.generated
     */
    private Date messageDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_message_manage.MESSAGE_DISABLE
     *
     * @mbg.generated
     */
    private String messageDisable;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_message_manage.MESSAGE_ID
     *
     * @return the value of g_message_manage.MESSAGE_ID
     *
     * @mbg.generated
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_message_manage.MESSAGE_ID
     *
     * @param messageId the value for g_message_manage.MESSAGE_ID
     *
     * @mbg.generated
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_message_manage.MESSAGE_PERSON_ID
     *
     * @return the value of g_message_manage.MESSAGE_PERSON_ID
     *
     * @mbg.generated
     */
    public String getMessagePersonId() {
        return messagePersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_message_manage.MESSAGE_PERSON_ID
     *
     * @param messagePersonId the value for g_message_manage.MESSAGE_PERSON_ID
     *
     * @mbg.generated
     */
    public void setMessagePersonId(String messagePersonId) {
        this.messagePersonId = messagePersonId == null ? null : messagePersonId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_message_manage.MESSAGE_PRODUCE_ID
     *
     * @return the value of g_message_manage.MESSAGE_PRODUCE_ID
     *
     * @mbg.generated
     */
    public String getMessageProduceId() {
        return messageProduceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_message_manage.MESSAGE_PRODUCE_ID
     *
     * @param messageProduceId the value for g_message_manage.MESSAGE_PRODUCE_ID
     *
     * @mbg.generated
     */
    public void setMessageProduceId(String messageProduceId) {
        this.messageProduceId = messageProduceId == null ? null : messageProduceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_message_manage.MESSAGE_INFO
     *
     * @return the value of g_message_manage.MESSAGE_INFO
     *
     * @mbg.generated
     */
    public String getMessageInfo() {
        return messageInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_message_manage.MESSAGE_INFO
     *
     * @param messageInfo the value for g_message_manage.MESSAGE_INFO
     *
     * @mbg.generated
     */
    public void setMessageInfo(String messageInfo) {
        this.messageInfo = messageInfo == null ? null : messageInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_message_manage.MESSAGE_DATE
     *
     * @return the value of g_message_manage.MESSAGE_DATE
     *
     * @mbg.generated
     */
    public Date getMessageDate() {
        return messageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_message_manage.MESSAGE_DATE
     *
     * @param messageDate the value for g_message_manage.MESSAGE_DATE
     *
     * @mbg.generated
     */
    public void setMessageDate(Date messageDate) {
        this.messageDate = messageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_message_manage.MESSAGE_DISABLE
     *
     * @return the value of g_message_manage.MESSAGE_DISABLE
     *
     * @mbg.generated
     */
    public String getMessageDisable() {
        return messageDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_message_manage.MESSAGE_DISABLE
     *
     * @param messageDisable the value for g_message_manage.MESSAGE_DISABLE
     *
     * @mbg.generated
     */
    public void setMessageDisable(String messageDisable) {
        this.messageDisable = messageDisable == null ? null : messageDisable.trim();
    }
}