package pers.guanzf.common.core.model;

import java.util.Date;

public class Produce {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_ID
     *
     * @mbg.generated
     */
    private String produceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_NAME
     *
     * @mbg.generated
     */
    private String produceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_TYPE
     *
     * @mbg.generated
     */
    private String produceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_PRICE
     *
     * @mbg.generated
     */
    private Float producePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_PURCHASE_TIMES
     *
     * @mbg.generated
     */
    private Integer producePurchaseTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_WEIGHT
     *
     * @mbg.generated
     */
    private Float produceWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_IMAGE_URL
     *
     * @mbg.generated
     */
    private String produceImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_NAV_IMG_URL
     *
     * @mbg.generated
     */
    private String produceNavImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.CREATE_DATE
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_PRAISE_NUM
     *
     * @mbg.generated
     */
    private Integer producePraiseNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_BAD_NUM
     *
     * @mbg.generated
     */
    private Integer produceBadNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_SELL_NUM
     *
     * @mbg.generated
     */
    private Integer produceSellNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_TODAY_NUM
     *
     * @mbg.generated
     */
    private Integer produceTodayNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.COMMODITY_STRUCTRUE_ID
     *
     * @mbg.generated
     */
    private String commodityStructrueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_DESC
     *
     * @mbg.generated
     */
    private String produceDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_produce.PRODUCE_USER_ID
     *
     * @mbg.generated
     */
    private String produceUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_ID
     *
     * @return the value of g_produce.PRODUCE_ID
     *
     * @mbg.generated
     */
    public String getProduceId() {
        return produceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_ID
     *
     * @param produceId the value for g_produce.PRODUCE_ID
     *
     * @mbg.generated
     */
    public void setProduceId(String produceId) {
        this.produceId = produceId == null ? null : produceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_NAME
     *
     * @return the value of g_produce.PRODUCE_NAME
     *
     * @mbg.generated
     */
    public String getProduceName() {
        return produceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_NAME
     *
     * @param produceName the value for g_produce.PRODUCE_NAME
     *
     * @mbg.generated
     */
    public void setProduceName(String produceName) {
        this.produceName = produceName == null ? null : produceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_TYPE
     *
     * @return the value of g_produce.PRODUCE_TYPE
     *
     * @mbg.generated
     */
    public String getProduceType() {
        return produceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_TYPE
     *
     * @param produceType the value for g_produce.PRODUCE_TYPE
     *
     * @mbg.generated
     */
    public void setProduceType(String produceType) {
        this.produceType = produceType == null ? null : produceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_PRICE
     *
     * @return the value of g_produce.PRODUCE_PRICE
     *
     * @mbg.generated
     */
    public Float getProducePrice() {
        return producePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_PRICE
     *
     * @param producePrice the value for g_produce.PRODUCE_PRICE
     *
     * @mbg.generated
     */
    public void setProducePrice(Float producePrice) {
        this.producePrice = producePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_PURCHASE_TIMES
     *
     * @return the value of g_produce.PRODUCE_PURCHASE_TIMES
     *
     * @mbg.generated
     */
    public Integer getProducePurchaseTimes() {
        return producePurchaseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_PURCHASE_TIMES
     *
     * @param producePurchaseTimes the value for g_produce.PRODUCE_PURCHASE_TIMES
     *
     * @mbg.generated
     */
    public void setProducePurchaseTimes(Integer producePurchaseTimes) {
        this.producePurchaseTimes = producePurchaseTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_WEIGHT
     *
     * @return the value of g_produce.PRODUCE_WEIGHT
     *
     * @mbg.generated
     */
    public Float getProduceWeight() {
        return produceWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_WEIGHT
     *
     * @param produceWeight the value for g_produce.PRODUCE_WEIGHT
     *
     * @mbg.generated
     */
    public void setProduceWeight(Float produceWeight) {
        this.produceWeight = produceWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_IMAGE_URL
     *
     * @return the value of g_produce.PRODUCE_IMAGE_URL
     *
     * @mbg.generated
     */
    public String getProduceImageUrl() {
        return produceImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_IMAGE_URL
     *
     * @param produceImageUrl the value for g_produce.PRODUCE_IMAGE_URL
     *
     * @mbg.generated
     */
    public void setProduceImageUrl(String produceImageUrl) {
        this.produceImageUrl = produceImageUrl == null ? null : produceImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_NAV_IMG_URL
     *
     * @return the value of g_produce.PRODUCE_NAV_IMG_URL
     *
     * @mbg.generated
     */
    public String getProduceNavImgUrl() {
        return produceNavImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_NAV_IMG_URL
     *
     * @param produceNavImgUrl the value for g_produce.PRODUCE_NAV_IMG_URL
     *
     * @mbg.generated
     */
    public void setProduceNavImgUrl(String produceNavImgUrl) {
        this.produceNavImgUrl = produceNavImgUrl == null ? null : produceNavImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.CREATE_DATE
     *
     * @return the value of g_produce.CREATE_DATE
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.CREATE_DATE
     *
     * @param createDate the value for g_produce.CREATE_DATE
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_PRAISE_NUM
     *
     * @return the value of g_produce.PRODUCE_PRAISE_NUM
     *
     * @mbg.generated
     */
    public Integer getProducePraiseNum() {
        return producePraiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_PRAISE_NUM
     *
     * @param producePraiseNum the value for g_produce.PRODUCE_PRAISE_NUM
     *
     * @mbg.generated
     */
    public void setProducePraiseNum(Integer producePraiseNum) {
        this.producePraiseNum = producePraiseNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_BAD_NUM
     *
     * @return the value of g_produce.PRODUCE_BAD_NUM
     *
     * @mbg.generated
     */
    public Integer getProduceBadNum() {
        return produceBadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_BAD_NUM
     *
     * @param produceBadNum the value for g_produce.PRODUCE_BAD_NUM
     *
     * @mbg.generated
     */
    public void setProduceBadNum(Integer produceBadNum) {
        this.produceBadNum = produceBadNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_SELL_NUM
     *
     * @return the value of g_produce.PRODUCE_SELL_NUM
     *
     * @mbg.generated
     */
    public Integer getProduceSellNum() {
        return produceSellNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_SELL_NUM
     *
     * @param produceSellNum the value for g_produce.PRODUCE_SELL_NUM
     *
     * @mbg.generated
     */
    public void setProduceSellNum(Integer produceSellNum) {
        this.produceSellNum = produceSellNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_TODAY_NUM
     *
     * @return the value of g_produce.PRODUCE_TODAY_NUM
     *
     * @mbg.generated
     */
    public Integer getProduceTodayNum() {
        return produceTodayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_TODAY_NUM
     *
     * @param produceTodayNum the value for g_produce.PRODUCE_TODAY_NUM
     *
     * @mbg.generated
     */
    public void setProduceTodayNum(Integer produceTodayNum) {
        this.produceTodayNum = produceTodayNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.COMMODITY_STRUCTRUE_ID
     *
     * @return the value of g_produce.COMMODITY_STRUCTRUE_ID
     *
     * @mbg.generated
     */
    public String getCommodityStructrueId() {
        return commodityStructrueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.COMMODITY_STRUCTRUE_ID
     *
     * @param commodityStructrueId the value for g_produce.COMMODITY_STRUCTRUE_ID
     *
     * @mbg.generated
     */
    public void setCommodityStructrueId(String commodityStructrueId) {
        this.commodityStructrueId = commodityStructrueId == null ? null : commodityStructrueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_DESC
     *
     * @return the value of g_produce.PRODUCE_DESC
     *
     * @mbg.generated
     */
    public String getProduceDesc() {
        return produceDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_DESC
     *
     * @param produceDesc the value for g_produce.PRODUCE_DESC
     *
     * @mbg.generated
     */
    public void setProduceDesc(String produceDesc) {
        this.produceDesc = produceDesc == null ? null : produceDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_produce.PRODUCE_USER_ID
     *
     * @return the value of g_produce.PRODUCE_USER_ID
     *
     * @mbg.generated
     */
    public String getProduceUserId() {
        return produceUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_produce.PRODUCE_USER_ID
     *
     * @param produceUserId the value for g_produce.PRODUCE_USER_ID
     *
     * @mbg.generated
     */
    public void setProduceUserId(String produceUserId) {
        this.produceUserId = produceUserId == null ? null : produceUserId.trim();
    }
}