package pers.guanzf.common.core.model;

import java.util.ArrayList;
import java.util.List;

public class SysDictExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public SysDictExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSysDictIdIsNull() {
            addCriterion("SYS_DICT_ID is null");
            return (Criteria) this;
        }

        public Criteria andSysDictIdIsNotNull() {
            addCriterion("SYS_DICT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSysDictIdEqualTo(String value) {
            addCriterion("SYS_DICT_ID =", value, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdNotEqualTo(String value) {
            addCriterion("SYS_DICT_ID <>", value, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdGreaterThan(String value) {
            addCriterion("SYS_DICT_ID >", value, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_DICT_ID >=", value, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdLessThan(String value) {
            addCriterion("SYS_DICT_ID <", value, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdLessThanOrEqualTo(String value) {
            addCriterion("SYS_DICT_ID <=", value, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdLike(String value) {
            addCriterion("SYS_DICT_ID like", value, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdNotLike(String value) {
            addCriterion("SYS_DICT_ID not like", value, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdIn(List<String> values) {
            addCriterion("SYS_DICT_ID in", values, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdNotIn(List<String> values) {
            addCriterion("SYS_DICT_ID not in", values, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdBetween(String value1, String value2) {
            addCriterion("SYS_DICT_ID between", value1, value2, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictIdNotBetween(String value1, String value2) {
            addCriterion("SYS_DICT_ID not between", value1, value2, "sysDictId");
            return (Criteria) this;
        }

        public Criteria andSysDictNameIsNull() {
            addCriterion("SYS_DICT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSysDictNameIsNotNull() {
            addCriterion("SYS_DICT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSysDictNameEqualTo(String value) {
            addCriterion("SYS_DICT_NAME =", value, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameNotEqualTo(String value) {
            addCriterion("SYS_DICT_NAME <>", value, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameGreaterThan(String value) {
            addCriterion("SYS_DICT_NAME >", value, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_DICT_NAME >=", value, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameLessThan(String value) {
            addCriterion("SYS_DICT_NAME <", value, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameLessThanOrEqualTo(String value) {
            addCriterion("SYS_DICT_NAME <=", value, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameLike(String value) {
            addCriterion("SYS_DICT_NAME like", value, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameNotLike(String value) {
            addCriterion("SYS_DICT_NAME not like", value, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameIn(List<String> values) {
            addCriterion("SYS_DICT_NAME in", values, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameNotIn(List<String> values) {
            addCriterion("SYS_DICT_NAME not in", values, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameBetween(String value1, String value2) {
            addCriterion("SYS_DICT_NAME between", value1, value2, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictNameNotBetween(String value1, String value2) {
            addCriterion("SYS_DICT_NAME not between", value1, value2, "sysDictName");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeIsNull() {
            addCriterion("SYS_DICT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeIsNotNull() {
            addCriterion("SYS_DICT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeEqualTo(String value) {
            addCriterion("SYS_DICT_TYPE =", value, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeNotEqualTo(String value) {
            addCriterion("SYS_DICT_TYPE <>", value, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeGreaterThan(String value) {
            addCriterion("SYS_DICT_TYPE >", value, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_DICT_TYPE >=", value, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeLessThan(String value) {
            addCriterion("SYS_DICT_TYPE <", value, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeLessThanOrEqualTo(String value) {
            addCriterion("SYS_DICT_TYPE <=", value, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeLike(String value) {
            addCriterion("SYS_DICT_TYPE like", value, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeNotLike(String value) {
            addCriterion("SYS_DICT_TYPE not like", value, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeIn(List<String> values) {
            addCriterion("SYS_DICT_TYPE in", values, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeNotIn(List<String> values) {
            addCriterion("SYS_DICT_TYPE not in", values, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeBetween(String value1, String value2) {
            addCriterion("SYS_DICT_TYPE between", value1, value2, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeNotBetween(String value1, String value2) {
            addCriterion("SYS_DICT_TYPE not between", value1, value2, "sysDictType");
            return (Criteria) this;
        }

        public Criteria andSysDictValueIsNull() {
            addCriterion("SYS_DICT_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andSysDictValueIsNotNull() {
            addCriterion("SYS_DICT_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andSysDictValueEqualTo(Integer value) {
            addCriterion("SYS_DICT_VALUE =", value, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueNotEqualTo(Integer value) {
            addCriterion("SYS_DICT_VALUE <>", value, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueGreaterThan(Integer value) {
            addCriterion("SYS_DICT_VALUE >", value, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("SYS_DICT_VALUE >=", value, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueLessThan(Integer value) {
            addCriterion("SYS_DICT_VALUE <", value, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueLessThanOrEqualTo(Integer value) {
            addCriterion("SYS_DICT_VALUE <=", value, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueIn(List<Integer> values) {
            addCriterion("SYS_DICT_VALUE in", values, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueNotIn(List<Integer> values) {
            addCriterion("SYS_DICT_VALUE not in", values, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueBetween(Integer value1, Integer value2) {
            addCriterion("SYS_DICT_VALUE between", value1, value2, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictValueNotBetween(Integer value1, Integer value2) {
            addCriterion("SYS_DICT_VALUE not between", value1, value2, "sysDictValue");
            return (Criteria) this;
        }

        public Criteria andSysDictSortIsNull() {
            addCriterion("SYS_DICT_SORT is null");
            return (Criteria) this;
        }

        public Criteria andSysDictSortIsNotNull() {
            addCriterion("SYS_DICT_SORT is not null");
            return (Criteria) this;
        }

        public Criteria andSysDictSortEqualTo(Integer value) {
            addCriterion("SYS_DICT_SORT =", value, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortNotEqualTo(Integer value) {
            addCriterion("SYS_DICT_SORT <>", value, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortGreaterThan(Integer value) {
            addCriterion("SYS_DICT_SORT >", value, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortGreaterThanOrEqualTo(Integer value) {
            addCriterion("SYS_DICT_SORT >=", value, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortLessThan(Integer value) {
            addCriterion("SYS_DICT_SORT <", value, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortLessThanOrEqualTo(Integer value) {
            addCriterion("SYS_DICT_SORT <=", value, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortIn(List<Integer> values) {
            addCriterion("SYS_DICT_SORT in", values, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortNotIn(List<Integer> values) {
            addCriterion("SYS_DICT_SORT not in", values, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortBetween(Integer value1, Integer value2) {
            addCriterion("SYS_DICT_SORT between", value1, value2, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictSortNotBetween(Integer value1, Integer value2) {
            addCriterion("SYS_DICT_SORT not between", value1, value2, "sysDictSort");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescIsNull() {
            addCriterion("SYS_DICT_TYPE_DESC is null");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescIsNotNull() {
            addCriterion("SYS_DICT_TYPE_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescEqualTo(String value) {
            addCriterion("SYS_DICT_TYPE_DESC =", value, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescNotEqualTo(String value) {
            addCriterion("SYS_DICT_TYPE_DESC <>", value, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescGreaterThan(String value) {
            addCriterion("SYS_DICT_TYPE_DESC >", value, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescGreaterThanOrEqualTo(String value) {
            addCriterion("SYS_DICT_TYPE_DESC >=", value, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescLessThan(String value) {
            addCriterion("SYS_DICT_TYPE_DESC <", value, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescLessThanOrEqualTo(String value) {
            addCriterion("SYS_DICT_TYPE_DESC <=", value, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescLike(String value) {
            addCriterion("SYS_DICT_TYPE_DESC like", value, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescNotLike(String value) {
            addCriterion("SYS_DICT_TYPE_DESC not like", value, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescIn(List<String> values) {
            addCriterion("SYS_DICT_TYPE_DESC in", values, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescNotIn(List<String> values) {
            addCriterion("SYS_DICT_TYPE_DESC not in", values, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescBetween(String value1, String value2) {
            addCriterion("SYS_DICT_TYPE_DESC between", value1, value2, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictTypeDescNotBetween(String value1, String value2) {
            addCriterion("SYS_DICT_TYPE_DESC not between", value1, value2, "sysDictTypeDesc");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableIsNull() {
            addCriterion("SYS_DICT_EDITABLE is null");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableIsNotNull() {
            addCriterion("SYS_DICT_EDITABLE is not null");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableEqualTo(Integer value) {
            addCriterion("SYS_DICT_EDITABLE =", value, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableNotEqualTo(Integer value) {
            addCriterion("SYS_DICT_EDITABLE <>", value, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableGreaterThan(Integer value) {
            addCriterion("SYS_DICT_EDITABLE >", value, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableGreaterThanOrEqualTo(Integer value) {
            addCriterion("SYS_DICT_EDITABLE >=", value, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableLessThan(Integer value) {
            addCriterion("SYS_DICT_EDITABLE <", value, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableLessThanOrEqualTo(Integer value) {
            addCriterion("SYS_DICT_EDITABLE <=", value, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableIn(List<Integer> values) {
            addCriterion("SYS_DICT_EDITABLE in", values, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableNotIn(List<Integer> values) {
            addCriterion("SYS_DICT_EDITABLE not in", values, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableBetween(Integer value1, Integer value2) {
            addCriterion("SYS_DICT_EDITABLE between", value1, value2, "sysDictEditable");
            return (Criteria) this;
        }

        public Criteria andSysDictEditableNotBetween(Integer value1, Integer value2) {
            addCriterion("SYS_DICT_EDITABLE not between", value1, value2, "sysDictEditable");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_sys_dict
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_sys_dict
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}