package pers.guanzf.common.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.guanzf.common.core.model.ProduceExample;
import pers.guanzf.common.core.model.info.ProduceInfo;

public interface ProduceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    long countByExample(ProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    int deleteByExample(ProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String produceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    int insert(ProduceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    int insertSelective(ProduceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    List<ProduceInfo> selectByExample(ProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    ProduceInfo selectByPrimaryKey(String produceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProduceInfo record, @Param("example") ProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProduceInfo record, @Param("example") ProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProduceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_produce
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProduceInfo record);
}