package pers.guanzf.common.core.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import pers.guanzf.common.core.model.PersonProduceExample;
import pers.guanzf.common.core.model.info.PersonProduceInfo;

public interface PersonProduceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    long countByExample(PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int deleteByExample(PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String personProduceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int insert(PersonProduceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int insertSelective(PersonProduceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    List<PersonProduceInfo> selectByExample(PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    PersonProduceInfo selectByPrimaryKey(String personProduceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PersonProduceInfo record, @Param("example") PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PersonProduceInfo record, @Param("example") PersonProduceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PersonProduceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_person_produce
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PersonProduceInfo record);
}