package pers.guanzf.common.core.model;

import java.util.ArrayList;
import java.util.List;

public class CommodityStructrueExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public CommodityStructrueExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommodityStructrueIdIsNull() {
            addCriterion("COMMODITY_STRUCTRUE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdIsNotNull() {
            addCriterion("COMMODITY_STRUCTRUE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_ID =", value, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdNotEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_ID <>", value, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdGreaterThan(String value) {
            addCriterion("COMMODITY_STRUCTRUE_ID >", value, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdGreaterThanOrEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_ID >=", value, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdLessThan(String value) {
            addCriterion("COMMODITY_STRUCTRUE_ID <", value, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdLessThanOrEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_ID <=", value, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdLike(String value) {
            addCriterion("COMMODITY_STRUCTRUE_ID like", value, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdNotLike(String value) {
            addCriterion("COMMODITY_STRUCTRUE_ID not like", value, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdIn(List<String> values) {
            addCriterion("COMMODITY_STRUCTRUE_ID in", values, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdNotIn(List<String> values) {
            addCriterion("COMMODITY_STRUCTRUE_ID not in", values, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdBetween(String value1, String value2) {
            addCriterion("COMMODITY_STRUCTRUE_ID between", value1, value2, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueIdNotBetween(String value1, String value2) {
            addCriterion("COMMODITY_STRUCTRUE_ID not between", value1, value2, "commodityStructrueId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameIsNull() {
            addCriterion("COMMODITY_STRUCTRUE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameIsNotNull() {
            addCriterion("COMMODITY_STRUCTRUE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_NAME =", value, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameNotEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_NAME <>", value, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameGreaterThan(String value) {
            addCriterion("COMMODITY_STRUCTRUE_NAME >", value, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameGreaterThanOrEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_NAME >=", value, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameLessThan(String value) {
            addCriterion("COMMODITY_STRUCTRUE_NAME <", value, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameLessThanOrEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_NAME <=", value, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameLike(String value) {
            addCriterion("COMMODITY_STRUCTRUE_NAME like", value, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameNotLike(String value) {
            addCriterion("COMMODITY_STRUCTRUE_NAME not like", value, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameIn(List<String> values) {
            addCriterion("COMMODITY_STRUCTRUE_NAME in", values, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameNotIn(List<String> values) {
            addCriterion("COMMODITY_STRUCTRUE_NAME not in", values, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameBetween(String value1, String value2) {
            addCriterion("COMMODITY_STRUCTRUE_NAME between", value1, value2, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueNameNotBetween(String value1, String value2) {
            addCriterion("COMMODITY_STRUCTRUE_NAME not between", value1, value2, "commodityStructrueName");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdIsNull() {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdIsNotNull() {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID =", value, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdNotEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID <>", value, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdGreaterThan(String value) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID >", value, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdGreaterThanOrEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID >=", value, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdLessThan(String value) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID <", value, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdLessThanOrEqualTo(String value) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID <=", value, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdLike(String value) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID like", value, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdNotLike(String value) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID not like", value, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdIn(List<String> values) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID in", values, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdNotIn(List<String> values) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID not in", values, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdBetween(String value1, String value2) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID between", value1, value2, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueFartherIdNotBetween(String value1, String value2) {
            addCriterion("COMMODITY_STRUCTRUE_FARTHER_ID not between", value1, value2, "commodityStructrueFartherId");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumIsNull() {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM is null");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumIsNotNull() {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM is not null");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumEqualTo(Integer value) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM =", value, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumNotEqualTo(Integer value) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM <>", value, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumGreaterThan(Integer value) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM >", value, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM >=", value, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumLessThan(Integer value) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM <", value, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumLessThanOrEqualTo(Integer value) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM <=", value, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumIn(List<Integer> values) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM in", values, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumNotIn(List<Integer> values) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM not in", values, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumBetween(Integer value1, Integer value2) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM between", value1, value2, "commodityStructrueChildNum");
            return (Criteria) this;
        }

        public Criteria andCommodityStructrueChildNumNotBetween(Integer value1, Integer value2) {
            addCriterion("COMMODITY_STRUCTRUE_CHILD_NUM not between", value1, value2, "commodityStructrueChildNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table g_commodity_structrue
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}